### PR TITLE
Add jpackage plugin for creating app distribution binaries

### PR DESCRIPTION
**Pull request by ElTitoDG**
I have added a plugin to use jpackage to distribute the app more easily using native binaries for each OS, for now I have only configured the mac version, but the config for windows and linux is missing.

There is also a new folder **res** that has the icons for each OS.

Refers to this issue #60

### CODE REVIEW

**Comment by ElTitoDG** [comment]
fast test on debian 12 arm vm and have errors

**Comment by privat** [comment]
Can you translate the description in english? (¡No hablo español!)
I tried on my combuter and got a 120MB deb file and no exe or dmg files. I'm not sure if this the expected behavior.

a good thing can be to update (or expands) the github actions and expose the installers as artifacts

**Comment by ElTitoDG** [comment]
Sorry for the stupid question, what description are you referring to?
About the deb file this should be the correct format as mentioned in this guide "On Linux, it defaults to deb for Debian Linux and rpm for other Linux versions". [Packaging Tool User's Guide](https://docs.oracle.com/en/java/javase/22/jpackage/packaging-tool-user-guide.pdf) according to the usual behavior on installation, it should be the normal one for deb packages, what worries me is the icon issue.

**Comment by privat** [comment]
the PR description, at https://github.com/privat/rars/pull/62

**Comment by ElTitoDG** [comment]
sorry dumb error

And regarding your test, that should be the behavior when building the package, at least happens the same for me in the mac

**Comment by ElTitoDG** [comment]
PR Status:

Currently it should work fine on all three platforms, on Mac it works perfectly including the icon being displayed, it would remain to do installation tests on the other platforms.


It works generating only the package of the host platform, where all use the same configuration, except for the icon that is based on profiles of each system.


The icon is a modification of this one [icon riscv](https://icon-icons.com/es/icono/Asamblea-RISCV/132573), and the license is [this one](https://creativecommons.org/licenses/by/4.0/)

**Comment by ElTitoDG** [comment]
Tested on my debian vm and builds and installs fine, I would only need someone testing it on windows and should be fine

**Comment by privat** [comment]
closed and reopenend to run tests again

**Pull request merged**
