### PR TITLE
Symbol coloring

### PR DESCRIPTION
**Pull request by Shin-703**
Just like with the label coloring, adds symbol coloring when a symbol has been declared with a ".eqv".

### CODE REVIEW

**Comment by privat** [comment]
maybe add a popup "please restart RARS to apply the new setting" or add "(restart required)" after the option name, otherwise it feels the option is broken.

**Comment by privat** [comment]
Could you update the PR to be compatible with #56?

**Comment by Shin-703** [comment]
Woops did not see you already added the newer commits

**Comment by Shin-703** [comment]
see PR #64

**Pull request closed without merging**
